### ISSUE TITLE
non-Heroku deployment

### ISSUE THREAD

**Issue by elricariocco** [developeranaz/RCLONE-SERVE-INDEX#22]
How would I go about it if I wanted to deploy somewhere different than heroku? For example, in https://replit.com/ I imported the repo and then clicked on "run" but nothing seems to happen. 
I would like to deploy there as I also deployed this [telegram index](https://github.com/elricariocco2/tg-index) which works nicely. Any help would be appreciated, thanks.
Btw my heroku account with this repo and [Aria2Rclone repo](https://github.com/developeranaz/URL-Magnet-Cloud-Uploader-Heroku) were deleted without notice (each repo was hosted in different account, the latter repo was deployed but never really used and still account got deleted). Perhaps heroku is banning Rclone things?

**Comment by developeranaz** [comment]
> How would I go about it if I wanted to deploy somewhere different than heroku? For example, in https://replit.com/ I imported the repo and then clicked on "run" but nothing seems to happen. I would like to deploy there as I also deployed this [telegram index](https://github.com/elricariocco2/tg-index) which works nicely. Any help would be appreciated, thanks. Btw my heroku account with this repo and [Aria2Rclone repo](https://github.com/developeranaz/URL-Magnet-Cloud-Uploader-Heroku) were deleted without notice (each repo was hosted in different account, the latter repo was deployed but never really used and still account got deleted). Perhaps heroku is banning Rclone things

I think repit doesn't support docker , this repo is working in docker , i never installed docker in replit, i don't know it is possible or not try it yourself
