### ISSUE TITLE
Is there any plan on support on other services?

### ISSUE THREAD

**Issue by jackthenewbie** [developeranaz/RCLONE-SERVE-INDEX#24]
Like glitch, railway, etc?

**Comment by developeranaz** [comment]
I think railway.app is possible.
But the glitch is a question mark for me

**Comment by jackthenewbie** [comment]
oki nice, I just got it run on railway:)case closed
oh and btw, if it deploy on heroku, is it always on 24/7? It would be nice if it wake up on request to be honest

> I think railway.app is possible. But the glitch is a question mark for me
